### ISSUE TITLE
add button to access tracker page on android tv

### ISSUE THREAD

**Issue by FrixBOX** [LagradOst/CloudStream-3#931]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- UI/UX enhancement

**Describe your request here** *(fill this up)*
- [x] How it works.
when i click the button it show the tracker page inside anime info like this:
![image](https://user-images.githubusercontent.com/97077814/162559358-c73fb73a-ff4f-4349-b6ba-e48bac8f9757.png)
- [x] Issues it solves.
i don't need to use external mouse to access it
- [x] Why it is needed.
i can't swipe my tv screen to access it

**Other related info**

**Comment by LagradOst** [comment]
Dude, pre is in development, this will be added

**Comment by FrixBOX** [comment]
i know it'll added eventually. but i'm just an impatient bastard
